---
title: "reads_coverage_go_terms"
author: "Sadik M"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load GO-terms annotation of Enset and Musa spp proteins 
```{r}

load("~/Downloads/OrthoFinder.EV.AED25.MAB.RData")
load("~/Downloads/OrthoFinder.EV.AED25.MAB.monocot.RData")

save(GO_terms_EV_AED25_MAB_v2,file = "GO_terms_EV_AED25_MAB_v2.RData")
save(GO_terms_EV_AED25_MAB_desc.v1,file = "GO_terms_EV_AED25_MAB_desc.v1.RData")


```

## Get gene IDs from annotation files and link with reads coverage across geneic regions and GO-term annotation
```{r}
# library(rtracklayer)

EV_MAB_genes <- list()


for (EACH_GFF_ANNOTATION in list.files(path = DATA_DIR, pattern = "gff3")){
  
  BASENAME <- basename(EACH_GFF_ANNOTATION) %>% str_remove(".gff3") %>% str_remove("EV_")

  read_gff <-
    rtracklayer::readGFF(paste0(DATA_DIR,EACH_GFF_ANNOTATION)) %>%
  as.data.frame() %>%
  dplyr::filter(type =='gene') %>%
  select(seqid,start,end,Name) %>%
    mutate(genome = BASENAME)

    EV_MAB_genes [[EACH_GFF_ANNOTATION]] <- read_gff # add it to your list

  
}

rm(read_gff)

EV_MAB_genes =
    do.call(rbind, EV_MAB_genes) %>%
  mutate(genome = str_remove(genome,".maker.annotation"))


# remove rownames 
rownames(EV_MAB_genes) <- NULL


# combine gene ID and reads coverage 

EV_MAB_reads_coverage_geneID <-
EV_MAB_genes %>% 
mutate(start = start -1) %>%
  left_join(
    EV_MAB_reads_coverage %>%
      mutate(
        
        reads_genome = str_replace_na(reads_genome, "NA"),
             start = as.numeric(start),
             end = as.numeric(end),
        genome = case_when(ref_genome=="musa_balbisiana" ~ "Musa_balbisiana",
                       ref_genome=="musa_acuminata" ~ "Musa_acuminata",
                       ref_genome=="ev_mazia" ~ "mazia",
                       ref_genome=="ev_bedadeti" ~ "bedadeti")) %>%
      dplyr::rename(seqid=seq.name)) 
  # filter(start==185298)

```


## add IntreProScan GO-terms annotation 
```{r}
EV_MAB_reads_coverage_geneID_GO_terms <-
  EV_MAB_reads_coverage_geneID %>%
  # rename gene ID of Musa acuminata (MA) and Musa balbisiana (MB) to match it with gene ID used in GO-terms analysis
  # Simple add a suffix of ".1" to each of MA and MB genes
  mutate(Name = case_when(genome == "Musa_acuminata" |
                            genome == "Musa_balbisiana" ~ str_c(Name,".1"),
                          TRUE ~ Name)) %>%
  dplyr::rename(genes=Name) %>%
  # Join GO-terms annotation
  left_join(
    GO_terms_EV_AED25_MAB_v2 %>% 
      mutate(genomes = str_remove(genomes,".AED25"),
             genes = str_remove(genes,"-\\w+")) %>%
      dplyr::rename(genome = genomes) %>%
      distinct()) %>%
  # filter(genome=="Musa_acuminata") %>% 
  mutate(GO_terms = str_replace_na(GO_terms,"NA")) %>%
  dplyr::rename(gene_id = genes)
  # head() %>%
  # filter(GO_terms != "NA")
```


## Filter EV and MAB specific genes 
### EV mazia specific genes 
```{r}
EV_MAB_reads_coverage_geneID_GO_terms %>%
  filter(ref_genome=="ev_mazia") %>%
  filter(fraction_overlap < 0.25 ) %>%
  head()
```

## update GO-terms annotation for non-syntenic genes

```{r}

# combine gene ID and reads coverage 

# EV_MAB_reads_coverage_geneID_synteny <-
# EV_MAB_genes %>% 
# mutate(start = start -1) %>%
#   left_join(
#     EV_MAB_reads_coverage_no_lastz_nucmer_alignment %>%
#   # filter(synteny=="non_syntenic") %>%
#       mutate(
#         genome = case_when(ref_genome=="musa_balbisiana" ~ "Musa_balbisiana",
#                        ref_genome=="musa_acuminata" ~ "Musa_acuminata",
#                        ref_genome=="ev_mazia" ~ "mazia",
#                        ref_genome=="ev_bedadeti" ~ "bedadeti")) %>%
#       dplyr::rename(seqid=seq.name)) %>%
#       mutate(V4 = str_replace_na(V4,'NA')) 

EV_MAB_reads_coverage_geneID_synteny <-
    EV_MAB_reads_coverage_no_lastz_nucmer_alignment %>%
  # filter(synteny=="non_syntenic") %>%
      mutate(
        genome = case_when(ref_genome=="musa_balbisiana" ~ "Musa_balbisiana",
                       ref_genome=="musa_acuminata" ~ "Musa_acuminata",
                       ref_genome=="ev_mazia" ~ "mazia",
                       ref_genome=="ev_bedadeti" ~ "bedadeti")) %>%
      dplyr::rename(seqid=seq.name) %>%
  left_join(
    EV_MAB_genes %>% 
      mutate(start = start -1)) %>%
      mutate(V4 = str_replace_na(V4,'NA')) 
    


EV_MAB_reads_coverage_geneID_GO_terms_synteny <-
  EV_MAB_reads_coverage_geneID_synteny %>%
  # rename gene ID of Musa acuminata (MA) and Musa balbisiana (MB) to match it with gene ID used in GO-terms analysis
  # Simple add a suffix of ".1" to each of MA and MB genes
  mutate(Name = case_when(genome == "Musa_acuminata" |
                            genome == "Musa_balbisiana" ~ str_c(Name,".1"),
                          TRUE ~ Name)) %>%
  dplyr::rename(genes=Name) %>%
  # Join GO-terms annotation
  left_join(
    GO_terms_EV_AED25_MAB_v2 %>% 
      mutate(genomes = str_remove(genomes,".AED25"),
             genes = str_remove(genes,"-\\w+")) %>%
      dplyr::rename(genome = genomes) %>%
      distinct()) %>%
  mutate(GO_terms = str_replace_na(GO_terms,"NA")) %>%
  dplyr::rename(gene_id = genes) %>%
  mutate (V7 = str_replace_na(V7,"NA")) %>%
  distinct()
  # head() %>%
  # filter(GO_terms != "NA")



        
      EV_MAB_reads_coverage_no_lastz_nucmer_alignment %>%
                # filter(end=="125076") 
      mutate(
        genome = case_when(ref_genome=="musa_balbisiana" ~ "Musa_balbisiana",
                       ref_genome=="musa_acuminata" ~ "Musa_acuminata",
                       ref_genome=="ev_mazia" ~ "mazia",
                       ref_genome=="ev_bedadeti" ~ "bedadeti")) %>%
      dplyr::rename(seqid=seq.name) %>%
                 filter(end=="125076") %>%

  left_join(
    EV_MAB_genes %>% 
      mutate(start = start -1)) %>%
      mutate(V4 = str_replace_na(V4,'NA')) 
      
      
       EV_MAB_genes %>% 
      mutate(start = start -1) %>%
         filter(end=="125076") 

               
```


